"""
AST-based scanner that reads the super_agent package and writes
data/CODEBASE.md — a compact self-description injected into every
system instruction so the agent knows its own code.
"""

from __future__ import annotations

import ast
import textwrap
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[3]
_PACKAGE_DIR = _REPO_ROOT / "super_agent"
_IGNORED_DIRS = {"__pycache__", ".venv", ".git", "node_modules"}


def _first_docstring(tree: ast.Module) -> str:
    for node in ast.walk(tree):
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
            s = str(node.value.value).strip()
            if s:
                return s.split("\n")[0][:120]
    return ""


def _top_level_names(tree: ast.Module) -> list[str]:
    names: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            doc = ast.get_docstring(node) or ""
            doc_short = doc.split("\n")[0][:80] if doc else ""
            names.append(f"  class {node.name}" + (f" — {doc_short}" if doc_short else ""))
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            doc = ast.get_docstring(node) or ""
            doc_short = doc.split("\n")[0][:80] if doc else ""
            names.append(f"  def {node.name}()" + (f" — {doc_short}" if doc_short else ""))
    return names


def _scan_package(package_dir: Path) -> dict[str, dict]:
    results: dict[str, dict] = {}
    for py in sorted(package_dir.rglob("*.py")):
        if any(p in py.parts for p in _IGNORED_DIRS):
            continue
        rel = py.relative_to(_REPO_ROOT)
        try:
            src = py.read_text(encoding="utf-8")
            tree = ast.parse(src)
            results[str(rel)] = {
                "lines": src.count("\n") + 1,
                "docstring": _first_docstring(tree),
                "symbols": _top_level_names(tree),
            }
        except SyntaxError:
            results[str(rel)] = {"lines": 0, "docstring": "(parse error)", "symbols": []}
    return results


def _layer_of(rel_path: str) -> str:
    parts = rel_path.split("/")
    for p in parts:
        if p in ("core", "domain", "infrastructure", "services", "api"):
            return p
    return "other"


_LAYER_DESC = {
    "core":           "Config, settings, Gemini client, security guards",
    "domain":         "Pure logic: HDC math, quantum scoring, chat/math schemas, blueprint status",
    "infrastructure": "Adapters: SymPy runner, intent router, HDC store, AST checker, git, Docker",
    "services":       "Orchestration: agent loop, orchestrator, sessions, heartbeat, SICA, research",
    "api":            "FastAPI routes, deps container, WebSocket stub",
    "other":          "Package init / main entrypoint",
}


def build_codebase_md(package_dir: Path = _PACKAGE_DIR) -> str:
    data = _scan_package(package_dir)
    layers: dict[str, list[tuple[str, dict]]] = {}
    for rel, info in data.items():
        lyr = _layer_of(rel)
        layers.setdefault(lyr, []).append((rel, info))

    lines: list[str] = [
        "# Super Agent — live codebase snapshot",
        "",
        "This file is auto-generated by `codebase_scanner.py` and injected into every",
        "system instruction so the agent knows its own architecture.",
        "",
        "## Architecture overview",
        "",
        "```",
        "super_agent/app/",
        "├── core/           Config, security, Gemini client + model fallback chain",
        "├── domain/         Pure logic: HDC (10k-dim VSA), quantum scoring, schemas",
        "├── infrastructure/ SymPy runner, intent router, HDC store, git, Docker",
        "├── services/       Orchestrator, session store, SICA loop, heartbeat, research",
        "└── api/            FastAPI routes + deps container",
        "data/               SOUL.md, MEMORY.md, HEARTBEAT.md, CODEBASE.md, sessions/",
        "tests/              pytest smoke + unit suite",
        "nextjstester/       Next.js 16 frontend (local tester)",
        "```",
        "",
        "## Runtime flow",
        "",
        "1. FastAPI receives `POST /api/v1/chat {message, session_id}`",
        "2. `SessionStore` loads prior conversation turns for this session",
        "3. `SuperAgentOrchestrator.run()` injects today's date + SOUL + MEMORY + this file",
        "4. `classify_intent()` routes: SYMBOLIC → SymPy codegen loop, NEURAL → Gemini",
        "5. Current-events keywords → `generate_with_search()` (Google Search grounding)",
        "6. Multi-turn history passed as `contents=[Content...]` to Gemini SDK",
        "7. Result stored in HDC associative memory (`data/hdc_memory.json`)",
        "8. Session turn saved to `data/sessions/<id>.json`",
        "",
        "## Key capabilities",
        "",
        "- **Self-aware**: knows its own file structure (this document)",
        "- **Multi-turn**: per-session conversation history backed to JSON",
        "- **Symbolic math**: Gemini generates SymPy → executed deterministically",
        "- **Search grounding**: current events queries use Google Search tool",
        "- **HDC memory**: 10 000-dim hypervectors for associative retrieval",
        "- **SICA loop**: self-assessment → plan JSON → AST check → git commit",
        "- **Heartbeat**: APScheduler reads HEARTBEAT.md every 30 min, updates MEMORY.md",
        "- **Model fallback**: 429/404 from primary model → tries fallback chain",
        "",
        "## Modules",
        "",
    ]

    order = ["core", "domain", "infrastructure", "services", "api", "other"]
    for lyr in order:
        if lyr not in layers:
            continue
        lines.append(f"### `{lyr}/` — {_LAYER_DESC.get(lyr, '')}")
        lines.append("")
        for rel, info in layers[lyr]:
            doc = info["docstring"]
            sym_lines = info["symbols"]
            header = f"**{rel}** ({info['lines']} lines)"
            if doc:
                header += f" — {doc}"
            lines.append(header)
            if sym_lines:
                lines.extend(sym_lines)
            lines.append("")

    return "\n".join(lines)


def refresh_codebase_md(data_dir: Path, package_dir: Path = _PACKAGE_DIR) -> Path:
    """Regenerate data/CODEBASE.md and return its path."""
    content = build_codebase_md(package_dir)
    out = data_dir / "CODEBASE.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    return out
